rvm:
  - 1.9.3
  - 2.1.8
  - 2.2.4
  - 2.3.0
matrix:
  fast_finish: true
  include:
    - rvm: 1.9.2
      gemfile: Gemfiles/Gemfile.1.9.2
services:
  - redis-server
before_install:
 - gem update bundler
